# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atos_Licitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField()),
                ('padrao', models.BooleanField()),
                ('nova_data', models.BooleanField()),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Atos de Licita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Modalidade_Licitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField()),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Modalidasdes de Licita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Tipos_de_Licitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('sigla', models.CharField(max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Licita\xe7\xe3o',
            },
        ),
    ]
