# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_licitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos_de_licitacao',
            name='sigla',
            field=models.CharField(max_length=10),
        ),
    ]
