# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0002_auto_20180617_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='atividades_secundarias',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
