# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_uf_cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField()),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uf_cidades.Estado')),
            ],
        ),
    ]
