# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fontes', '0002_auto_20180728_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonte',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uf_cidades.Estado'),
        ),
    ]
