# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=150)),
                ('fantasia', models.CharField(blank=True, max_length=300, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=300, null=True)),
                ('atividade_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('atividades_secundarias', models.CharField(blank=True, max_length=1500000, null=True)),
                ('capital_social', models.CharField(blank=True, max_length=150, null=True)),
                ('data_situacao', models.CharField(blank=True, max_length=150, null=True)),
                ('uf', models.CharField(blank=True, max_length=150, null=True)),
                ('natureza_juridica', models.CharField(blank=True, max_length=150, null=True)),
                ('abertura', models.CharField(blank=True, max_length=150, null=True)),
                ('situacao', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
