# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orgao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='razao_social',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
